Added new country test
tysonwolker/front-end-challenge pull request #1
Opened 2020-11-22 22:41 UTC by tysonwolker

It's a new test, please review everything from the language to the test itself. I've forked this, so once everyone is happy I'll merge this to my own master before doing another PR for the final change to master of the q-ctrl repo. I'd rather constructive feedback is done here than in the q-ctrl repo.

2020-11-22 22:58 UTC, charmasaur reviewed
Challenge seems reasonable to me (not that I'd really know), just left a couple of comments about wording.

2020-11-22 22:58 UTC, charmasaur commented on README.md
> +Then I should check if the country's name contains the search text
It's not clear to me what this means. Can we rephrase it in terms of what the user will see?

2020-11-22 22:58 UTC, charmasaur commented on README.md
> +The first feature is to create a page where a customer can view all the countries that are returned from the countries API. Create a web application using [React](https://reactjs.org/) that satisfies
nit: IMO the structure here is a little unclear, because the reference to creating a web application using React is in this "countries page" section, even though it also applies to the "country page". How about changing it to something like:
```
## The Requirements
Create a web application using [React](https://reactjs.org/) consisting of two pages, as describe below.

### Countries Page
The first page allows a customer to view all the countries that are returned from the countries API, and satisfies the following scenarios:
...

### Country Page
The second page allows a customer to view details about an individual country, and satisfies the following scenarios:
...
```

2020-11-23 00:14 UTC, robertlove requested changes

2020-11-23 00:14 UTC, robertlove commented on README.md
> +Given I am on the countries page
"countries page" or "Countries page". Choose one. Use consistently.

2020-11-23 00:14 UTC, robertlove commented on README.md
> +Then I should check if the country's name contains the search text
Agree. There are a few here that need rewriting from the customers perspective.

"And display their country name"
"Then hide the next page button"
"Then hide the previous page button"
"Then take me to the country page"
etc...

2020-11-23 12:25 UTC, tysonwolker commented
@robertlove & @charmasaur thanks for your comments, I learnt a few things for my own benefit too. Have updated the PR appropriately.

2020-11-23 22:17 UTC, charmasaur reviewed
LGTM, just some nitpicks

2020-11-23 22:17 UTC, charmasaur commented on README.md
>  - Read and understand [The Challenge](#the-challenge)
```suggestion
- Read and understand [The challenge](#the-challenge)
```

2020-11-23 22:17 UTC, charmasaur commented on README.md
>  - Create solutions that satisfy [The Requirements](#the-requirements)
```suggestion
- Create solutions that satisfy [The requirements](#the-requirements)
```

2020-11-23 22:17 UTC, charmasaur commented on README.md
> +Using the following endpoint to [get the list of all countries](https://restcountries.eu/rest/v2/all).
nit: "Using the following" reads a little strangely when the link is part of the text like this. How about:
```suggestion
Use the [RESTCountries endpoint](https://restcountries.eu/rest/v2/all) to get the list of all countries.
```

2020-11-23 22:42 UTC, merged